### ISSUE TITLE
[Feature] Optional parameters

### ISSUE THREAD

**Issue by nbrugger-tgm** [cliserkad/kdl#19]
**Related problem / error / bug**
In java i am only missing one mayor feature. Optional parameters. I do not know why java is lacking this feature as it violates not rules java is built around and could easily achived using a pre-processor

**Solution**
I would prefere
```java
void foo(int a,int b = 12){ ... }
```
over
```java
void foo(int a){ foo(a,12); }
void foo(int a, int b){ ... }
```
**Alternatives**

* Using pre-processed/compiled annotations eg (`void foo(int a,@default(12) int b) `
* using a keyword eg `void foo(int a,int default(12) b)`

**Comment by cliserkad** [comment]
Yes, optional (default) parameters are a feature of kdl. It doesn't use a preprocessor because that would limit it to literals. For each default the expression, such as `12` or `id() + 3`, a helper method is made containing the expression's operations. The caller must detect when this helper method exists and inject the helper method before the explicit method call. I'll add annotations so that the defaults are easier to read for external tools.

Look at https://github.com/cliserkad/kdl/blob/08dca8954909509a35f61dce83539364396c15ab/java-compiler/src/test/kdl/basics/defaults/FibDefaults.kdl for an example of how to write it

**Comment by nbrugger-tgm** [comment]
In the context of this is it possible to use the KDL compiler to compile default .java files just using the optional parameter feature?

**Comment by cliserkad** [comment]
No, it's a separate language. Currently, it's lacking inheritance so I don't recommend you use it at all.
